on: workflow_dispatch
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        run: npm install
      - name: npm start
        run: npm start $username $wxKey
        env:
          username: ${{github.repository_owner}}
          wxKey: ${{secrets.WX_KEY}}
          GITHUB_TOKEN: ${{secrets.TOKEN}}
